[package]
name = "portwatch-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
portwatch = { path = ".." }
libfuzzer-sys = { path = "libfuzzer-sys" }

[workspace]

[profile.release]
debug = 1
overflow-checks = true
panic = "abort"

[[bin]]
name = "stream_fuzzer"
path = "fuzz_targets/stream_fuzzer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "manifest_fuzzer"
path = "fuzz_targets/manifest_fuzzer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "ledger_fuzzer"
path = "fuzz_targets/ledger_fuzzer.rs"
test = false
doc = false
bench = false
